name: Freeze Dependencies

on:
  workflow_dispatch:  # esto permite ejecutarlo manualmente desde la pestaña "Actions"

jobs:
  freeze:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias desde requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generar pip freeze
        run: pip freeze > frozen_requirements.txt

      - name: Subir archivo freeze al repositorio
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add frozen_requirements.txt
          git commit -m "Freeze actualizado automáticamente"
          git push
